train:
  verbose: true

  data_dir: /home/giully/Programmazione/calib_challenge/src/data3_crop
  train_videos: [0, 1, 3, 4] #[0, 1, 3, 4]
  videos_parts: [[0, 1], [0, 1], [0, 1, 2], [0, 1]] #[[0, 1], [0, 1], [0, 1, 2, 3], [0, 1]]
  
  range: null #range of frames for each dataset

  valid_model: false
  valid_video: null
  valid_part: null
  
  test_model: false
  test_video: null 
  test_part: null

  deterministic: true
  debug: false

  frame_size: [88, 311] #[291, 388]

  consecutive_frames: 10
  skips: 1
  
  batch_size: 16 #16 batch should be better
  shuffle: false
  persistent_workers: true
  train_workers: 4
  valid_workers: 0
  test_workers: 0

  lstm_hidden_size: 172
  lstm_num_layers: 1

  linear_layers: [256, 128, 64] #consider only the hidden linear layers. For the input/output layers the model will deduce the right parameters.
  
  loss: "mse"

  opt: sgd
  lr: 0.001

  scheduler_gamma: 1
  scheduler_epochs: [0]

  epochs: 10

  training_info_dir: /home/giully/Programmazione/calib_challenge/src/test_6

  history_active: true
  history_save_train_info: true
  history_save_model: false

  activation_map_active: true
  activation_map_layers: ["conv1", "elu1", "conv2"]
  activation_map_dss: [0, 1] #dataset
  activation_map_frames: [[0, 1, 2, 3], [20, 21]]
  
  
  grad_flow_active: true
  grad_flow_epochs: 1