train:
  verbose: true

  data: /home/giully/Programmazione/calib_challenge/src/data3_crop
  train_videos: [0, 1, 3, 4] #[0, 1, 3, 4]
  videos_parts: [[0, 1], [0, 1], [0, 1, 2, 3], [0, 1]] #[[0, 1], [0, 1], [0, 1, 2, 3], [0, 1]]
  
  range: null

  valid_model: false
  valid_video: [0, 1, 3, 4]
  valid_part: [2, 2, 3, 2]
  
  test_model: false
  test_video: 2
  test_part: 1

  deterministic: true
  debug: false

  frame_size: [88, 311] #[291, 388]

  consecutive_frames: 10
  skips: 1
  
  batch_size: 16 #16 batch should be better
  shuffle: false
  persistent_workers: True
  train_workers: 4
  valid_workers: 0
  test_workers: 0

  lstm_hidden_size: 172
  lstm_num_layers: 1

  linear_layers: [256, 128, 64] #consider only the hidden linear layers. For the input/output layers the model will deduce the right parameters.

  
  opt: adam
  lr: 0.0001

  epochs: 30

  training_info_dir: /home/giully/Programmazione/calib_challenge/src/test_4_15

  save_history: true
  save_model: false

  activation_maps: ["conv1", "elu1", "conv2"]
  grad_flow: True