train:
  verbose: true

  # training_dirs: [/home/giully/Programmazione/calib_challenge/src/training_data/data_crop, 
  #                 /home/giully/Programmazione/calib_challenge/src/training_data/data_jitter_blur,
  #                 /home/giully/Programmazione/calib_challenge/src/training_data/data_rotation,
  #                 /home/giully/Programmazione/calib_challenge/src/training_data/data_translate,
  #                 /home/giully/Programmazione/calib_challenge/src/training_data/data_affine]

  training_dirs: [/home/giully/Programmazione/calib_challenge/src/training_data/data_crop,
                  /home/giully/Programmazione/calib_challenge/src/training_data/data_affine,
                  /home/giully/Programmazione/calib_challenge/src/training_data/data_jitter_blur]

  train_videos: [0, 1, 3, 4]
  videos_parts: [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2], [0, 1, 2, 3, 4, 5]] 
  
  shuffle_parts: true

  range: null #range of frames for each dataset

  valid_model: true
  valid_dirs: [/home/giully/Programmazione/calib_challenge/src/validation_data/data_crop]
  valid_videos: [0, 1, 3, 4]
  valid_parts: [[6], [6], [4], [6]]
  
  test_model: true
  test_dir: /home/giully/Programmazione/calib_challenge/src/test_data
  test_video: 2 

  deterministic: false
  debug: false

  frame_size: [291, 388] #[116, 311] 

  consecutive_frames: 10
  skips: 1

  dataset: diskvideods
  
  batch_size: 16
  shuffle: true
  persistent_workers: true
  train_workers: 4
  valid_workers: 0
  test_workers: 0

  lstm_hidden_size: 32
  lstm_num_layers: 1
  lstm_dropout: 0

  linear_dropout: 0
  #consider only the hidden linear layers. For the input/output layers the model will deduce the right parameters.
  linear_layers: [] 
  
  loss: mse

  opt: adam
  lr: 0.0003
  weight_decay: 0.001

  scheduler_gamma: 1
  scheduler_epochs: [0]

  epochs: 10

  training_info_dir: /home/giully/Programmazione/calib_challenge/src/valid_test_results/test_2

  history_active: true
  history_save_train_info: true
  history_save_model: false

  activation_map_active: true
  activation_map_layers: ["conv1", "elu1", "conv2"]
  activation_map_valid_ds: [0, 1, 2] #dataset 
  activation_map_valid_frames: [[0, 1], [0, 1], [0, 1]]
  activation_map_test: true
  activation_map_test_frames: [0, 30, 50] 

  
  grad_flow_active: true
  grad_flow_epochs: 3


transformations:
  color_jitter: false
  brightness: [1, 3]
  contrast: [1, 3]
  saturation: 0
  hue: 0

  rotation: false
  degrees: [-15, 15]

  translate: false
  translations: [0.1, 0.1]

  crop: true
  crop_args: [112, 232, 39, 349] 
  crop_size: [120, 310]

  horizontal_flip: false
  vertical_flip: false
  gauss_blur: false

  transforms: null #[[rotation, crop, color_jitter], [translate, crop, color_jitter]]

