train:
  verbose: true

  data_dir: /home/giully/Programmazione/calib_challenge/src/data3_crop
  train_videos: [0, 1] #[0, 1, 3, 4]
  videos_parts: [[0, 1], [0, 1]] #[[0, 1], [0, 1], [0, 1, 2, 3], [0, 1]]
  
  range: null #range of frames for each dataset

  valid_model: false
  valid_video: null
  valid_part: null
  
  test_model: false
  test_video: null 
  test_part: null

  deterministic: true
  debug: true

  frame_size: [88, 311] #[291, 388]

  consecutive_frames: 10
  skips: 1
  
  batch_size: 32 #16 batch should be better
  shuffle: true
  persistent_workers: true
  train_workers: 4
  valid_workers: 0
  test_workers: 0

  lstm_hidden_size: 64
  lstm_num_layers: 2

  linear_layers: [100] #consider only the hidden linear layers. For the input/output layers the model will deduce the right parameters.
  
  loss: "rmse"

  opt: adam
  lr: 0.0001

  scheduler_gamma: 1
  scheduler_epochs: [0]

  epochs: 20

  training_info_dir: /home/giully/Programmazione/calib_challenge/src/test_results/test_8

  history_active: true
  history_save_train_info: true
  history_save_model: false

  activation_map_active: false
  activation_map_layers: ["conv1", "elu1", "conv2"]
  activation_map_dss: [0] #dataset index
  activation_map_frames: [[30, 342]]
  
  
  grad_flow_active: true
  grad_flow_epochs: 4