train:
  verbose: true

  data: C:\Users\Giully\Programmazione\calib_challenge\src\data3
  train_videos: [0] #[0, 1, 3, 4]
  videos_parts: [[0]] #[[0], [0], [0, 1, 2, 3], [0, 1]]
  
  range: [0, 512]

  valid_model: false
  valid_video: 2
  valid_part: 0
  
  test_model: false
  test_video: 2
  test_part: 1

  deterministic: true

  frame_size: [291, 388]

  consecutive_frames: 5
  skips: 1
  
  batch_size: 16 #16 batch should be better
  shuffle: false
  persistent_workers: false
  train_workers: 0
  valid_workers: 0
  test_workers: 0

  lstm_hidden_size: 128
  lstm_num_layers: 1

  linear_layers: [] #consider only the hidden linear layers. For the input/output layers the model will deduce the right parameters.

  
  opt: adam
  lr: 0.0001

  epochs: 50

  training_info_dir: C:\Users\Giully\Programmazione\calib_challenge\src\test_1

  save_history: true
  save_model: false

  activation_maps: ["conv1", "conv2"]
  grad_flow: True