augment:
  data_dir: /home/giully/Programmazione/calib_challenge/src/data
  videos: [0, 1, 3, 4]
  videos_parts: [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2], [0, 1, 2, 3, 4, 5]] 

  output_dir: /home/giully/Programmazione/calib_challenge/src/training_data/data_affine


transformations:
  color_jitter: true
  brightness: [2, 3.5]
  contrast: [0.8, 1.5]
  saturation: 0
  hue: 0

  affine: true
  rotation: false
  degrees: [-20, 20]
  translate: false
  translations: [0.15, 0.15]

  crop: true
  crop_args: [112, 232, 39, 349] 

  gauss_blur: false
  sigma: 1


  horizontal_flip: false
  vertical_flip: false
  
  transforms: [affine, crop]
