conversion:
  input: /home/giully/Programmazione/calib_challenge/src/videos/labeled
  output: /home/giully/Programmazione/calib_challenge/src/data
  selected_frames: /home/giully/Programmazione/calib_challenge/src/config/selected_frames
  videos: [0, 1, 2, 3, 4]
  height_divisor: 3
  width_divisor: 3
  yuv: true 