train:
  data: tensors
  train_videos: [0] #[0, 1, 3, 4]
  videos_parts: [[0]] #[[0], [0], [0, 1, 2, 3], [0, 1]]
  
  #temporary solution. 
  range: [0, 32]

  valid_model: false
  valid_video: 2
  valid_part: 0
  
  test_model: false
  test_video: 2
  test_part: 1

  deterministic: true

  frame_size: [291, 388]

  consecutive_frames: 8
  skips: 1
  
  batch_size: 8
  shuffle: false
  persistent_workers: false
  train_workers: 0
  valid_workers: 0
  test_workers: 0

  
  opt: adam
  lr: 0.0003

  epochs: 10

  verbose: true
  training_info_dir: out_dir

  save_history: true
  save_model: false

  activation_map: ["conv1", "elu1"]