train:
  data: tensors
  train_videos: [3] #[0, 1, 3, 4]
  videos_parts: [[0]] #[[0], [0], [0, 1, 2, 3], [0, 1]]
  
  valid_model: false
  valid_video: 2
  valid_part: 0
  
  test_model: false
  test_video: 2
  test_part: 1

  deterministic: true

  frame_size: [291, 388]
  
  batch_size: 32
  shuffle: false
  persistent_workers: false
  train_workers: 0
  valid_workers: 0
  test_workers: 0

  
  opt: adam
  lr: 0.0003

  epochs: 10

  verbose: true
  history_out: out_dir
  save_history: true
  save_model: false
