train:
  data: /home/giully/Programmazione/calib_challenge/src/data3
  train_videos: [0, 1] #[0, 1, 3, 4]
  videos_parts: [[0, 1], [0]] #[[0], [0], [0, 1, 2, 3], [0, 1]]
  
  valid_model: false
  valid_video: 2
  valid_part: 0
  
  test_model: false
  test_video: 2
  test_part: 1

  deterministic: true

  frame_size: [291, 388] #[437, 582] #/2   #[291, 388] /3    Height, width

  consecutive_frames: 8
  skips: 1
  
  batch_size: 32
  shuffle: false
  persistent_workers: true
  train_workers: 6
  valid_workers: 0
  test_workers: 0

  
  opt: adam
  lr: 0.0001

  epochs: 20

  verbose: true
  history_out: /home/giully/Programmazione/calib_challenge/src/test_2
  save_history: true
  save_model: false
